server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/dev/{application}
        git:
          uri: https://gitlab.daumsoft.com/dast/dataplus/config/
          search-paths: 'dev/'
  profiles:
    active: native
  security:
    user:
      name: user
      password: password
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/